/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'error-container': '#ffdad6',
        'on-background': '#191c1d',
        'surface-variant': '#e1e3e4',
        'on-primary-fixed': '#001c3a',
        'on-primary-fixed-variant': '#004785',
        'inverse-surface': '#2e3132',
        'primary': '#004581',
        'on-tertiary-fixed-variant': '#763300',
        'on-error': '#ffffff',
        'background': '#f8f9fa',
        'on-secondary-fixed': '#1a1c1c',
        'surface-container-low': '#f3f4f5',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#e2e2e2',
        'on-primary-container': '#bed7ff',
        'on-primary': '#ffffff',
        'on-surface': '#191c1d',
        'surface-container': '#edeeef',
        'inverse-on-surface': '#f0f1f2',
        'secondary-fixed-dim': '#c6c6c7',
        'on-error-container': '#93000a',
        'surface-container-high': '#e7e8e9',
        'on-secondary-container': '#616363',
        'surface-container-highest': '#e1e3e4',
        'on-tertiary-fixed': '#331200',
        'tertiary': '#733200',
        'primary-fixed': '#d4e3ff',
        'on-surface-variant': '#414751',
        'surface-bright': '#f8f9fa',
        'inverse-primary': '#a5c8ff',
        'on-tertiary-container': '#ffcaad',
        'outline-variant': '#c1c6d3',
        'primary-fixed-dim': '#a5c8ff',
        'tertiary-container': '#974401',
        'surface': '#f8f9fa',
        'surface-tint': '#075fac',
        'primary-container': '#005daa',
        'secondary-container': '#dfe0e0',
        'on-secondary-fixed-variant': '#454747',
        'secondary': '#5d5f5f',
        'surface-dim': '#d9dadb',
        'outline': '#727782',
        'tertiary-fixed': '#ffdbc9',
        'on-tertiary': '#ffffff',
        'error': '#ba1a1a',
        'tertiary-fixed-dim': '#ffb68d',
      },
      spacing: {
        'stack-lg': '24px',
        'stack-md': '16px',
        'stack-sm': '8px',
        'gutter': '24px',
        'margin': '32px',
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
